export const LANDING = '/'
export const DASHBOARDS = '/dashboards'
export const SIGNIN = '/signin'
export const SIGNUP = '/signup'
export const CREATEVACATIONDETAILS = '/createVacationDetails'
export const CURRENTVACATIONSDASHBOARDS = '/dashboards/current'
export const PASTVACATIONSDASHBOARDS = '/dashboards/past'
export const VACATIONDETAILS = '/createVacationDetails'